<?php

namespace App\Services;

class TemplateLibraryService
{
    private static array $templates = [
        'dz-invoice-a4' => [
            'name'          => 'فاتورة بيع A4',
            'doc_type_code' => 'FV',
            'paper_size'    => 'A4',
            'is_default'    => false,
            'is_active'     => true,
            'config'        => [
                'paper_width_mm'       => 80,
                'page_orientation'     => 'portrait',
                'margin_top'           => 20,
                'margin_bottom'        => 20,
                'margin_sides'         => 18,
                'line_spacing'         => 1.2,
                'base_font_size'       => 9.5,
                'font_family'          => 'tajawal',
                'show_logo'            => true,
                'logo_source'          => 'company',
                'custom_logo_url'      => null,
                'logo_size'            => 75,
                'logo_align'           => 'left',
                'logo_border_radius'   => 0,
                'show_company_name'    => true,
                'company_name_text'    => '',
                'company_name_size'    => 16,
                'company_name_bold'    => true,
                'company_name_align'   => 'right',
                'company_name_color'   => '#1a1a2e',
                'show_address'         => true,
                'show_phone'           => true,
                'show_tax_id'          => true,
                'show_rc'              => true,
                'show_nis'             => true,
                'show_ice'             => true,
                'show_article'         => true,
                'show_activity'        => true,
                'company_info_align'   => 'right',
                'company_info_size'    => 8.5,
                'header_custom_text'   => '',
                'header_separator'     => 'solid',
                'title_text'           => 'فاتورة بيع',
                'title_size'           => 20,
                'title_bold'           => true,
                'title_align'          => 'center',
                'title_color'          => '#1a1a2e',
                'show_doc_number'      => true,
                'show_date'            => true,
                'show_time'            => false,
                'show_due_date'        => true,
                'show_cashier'         => true,
                'show_client'          => true,
                'show_client_nif'      => true,
                'show_client_phone'    => true,
                'show_client_address'  => true,
                'show_customer_commercial_name' => true,
                'show_customer_rc'     => true,
                'show_customer_nis'    => true,
                'show_customer_ai'     => true,
                'show_delivery_address'=> false,
                'show_session'         => false,
                'show_payment_term'    => false,
                'show_bank_details'    => true,
                'bank_details_text'    => 'RIB: 007 99999 000012345678 90',
                'doc_separator'        => 'solid',
                'col_order'            => ['ref','name','quantity','price','tva','total'],
                'col_show'             => ['ref'=>true,'name'=>true,'quantity'=>true,'price'=>true,'tva'=>true,'total'=>true],
                'col_widths'           => ['ref'=>8,'name'=>28,'quantity'=>10,'price'=>18,'tva'=>12,'total'=>18],
                'col_headers'          => ['ref'=>'م','name'=>'البيان','quantity'=>'الكمية','price'=>'س.و.ح','tva'=>'%TVA','total'=>'المبلغ'],
                'col_aligns'           => ['ref'=>'center','name'=>'right','quantity'=>'center','price'=>'center','tva'=>'center','total'=>'center'],
                'items_font_size'      => 9,
                'items_font_family'    => 'tajawal',
                'show_col_header'      => true,
                'table_header_bold'    => true,
                'table_header_bg'      => '#1a1a2e',
                'table_header_color'   => '#ffffff',
                'table_border_style'   => 'solid',
                'alternating_rows'     => true,
                'alternating_color'    => '#f8f9fa',
                'price_display'        => 'ht',
                'show_line_total_ttc'  => false,
                'totals_font_size'     => 10,
                'totals_bold'          => true,
                'totals_align'         => 'left',
                'show_total_ht'        => true,
                'show_total_tva'       => true,
                'show_tva_breakdown'   => true,
                'show_discount_total'  => true,
                'show_fiscal_stamp'    => true,
                'show_total_ttc'       => true,
                'total_ttc_font_size'  => 17,
                'total_ttc_bold'       => true,
                'total_ttc_color'      => '#1a1a2e',
                'total_border_style'   => 'double',
                'show_amount_in_words' => true,
                'show_paid_amount'     => false,
                'show_change'          => false,
                'show_remaining'       => false,
                'show_prev_balance'    => false,
                'show_new_balance'     => false,
                'show_payment_details' => true,
                'payment_font_size'    => 9,
                'footer_line1'         => 'البضاعة المباعة لا ترد ولا تستبدل',
                'footer_line2'         => 'للاستفسار اتصل على: 0550 00 00 00',
                'footer_line3'         => '',
                'footer_separator'     => 'solid',
                'show_thank_you'       => true,
                'thank_you_text'       => 'شكراً لتعاملكم',
                'thank_you_size'       => 11,
                'thank_you_color'      => '#333333',
                'show_returns_policy'  => true,
                'returns_policy_text'  => 'البضاعة المباعة لا ترد ولا تستبدل',
                'footer_legal_text'    => '',
                'show_barcode'         => true,
                'barcode_content'      => 'doc-number',
                'barcode_custom_text'  => '',
                'show_qr'              => true,
                'qr_content'           => 'both',
                'show_cashier_signature'=> true,
                'show_client_signature' => true,
                'show_stamp'           => true,
                'show_header_section'  => true,
                'show_doc_info_section'=> true,
                'show_items_section'   => true,
                'show_totals_section'  => true,
                'show_payments_section'=> false,
                'show_footer_section'  => true,
                'rules'                => [],
                'header_layout' => [
                    'mode' => 'columns',
                    'columns' => [
                        [
                            'id' => 'col_company_info', 'order' => 0, 'visible' => true,
                            'width' => 34, 'align' => 'start',
                            'padding' => ['top' => 0, 'end' => 6, 'bottom' => 0, 'start' => 10],
                            'rows' => [
                                ['id' => 'r1', 'field' => 'company.phone',   'label' => 'هاتف',   'visible' => true, 'order' => 0, 'labelSide' => 'start', 'valueSide' => 'end'],
                                ['id' => 'r2', 'field' => 'company.mobile',  'label' => 'محمول',  'visible' => true, 'order' => 1, 'labelSide' => 'start', 'valueSide' => 'end'],
                                ['id' => 'r3', 'field' => 'company.nif',    'label' => 'NIF',    'visible' => true, 'order' => 2, 'labelSide' => 'start', 'valueSide' => 'end'],
                                ['id' => 'r4', 'field' => 'company.rc',     'label' => 'RC',     'visible' => true, 'order' => 3, 'labelSide' => 'start', 'valueSide' => 'end'],
                                ['id' => 'r5', 'field' => 'company.nis',    'label' => 'NIS',    'visible' => true, 'order' => 4, 'labelSide' => 'start', 'valueSide' => 'end'],
                                ['id' => 'r6', 'field' => 'company.ice',    'label' => 'ICE',    'visible' => true, 'order' => 5, 'labelSide' => 'start', 'valueSide' => 'end'],
                            ],
                        ],
                        [
                            'id' => 'col_company_name', 'order' => 1, 'visible' => true,
                            'width' => 36, 'align' => 'center',
                            'padding' => ['top' => 0, 'end' => 6, 'bottom' => 0, 'start' => 6],
                            'titleField' => 'company.name',
                            'titleStyle' => ['bold' => true, 'fontSize' => 18],
                            'rows' => [
                                ['id' => 'addr', 'field' => 'company.address', 'visible' => true, 'order' => 0, 'labelSide' => 'start', 'valueSide' => 'start', 'label' => ''],
                            ],
                        ],
                        [
                            'id' => 'col_reference_box', 'order' => 2, 'visible' => true,
                            'width' => 30, 'align' => 'start',
                            'border' => ['style' => 'solid', 'width' => 1, 'color' => '#333333', 'radius' => 4],
                            'padding' => ['top' => 8, 'end' => 10, 'bottom' => 8, 'start' => 10],
                            'rows' => [
                                ['id' => 'num',  'field' => 'document.number', 'label' => 'رقم الفاتورة', 'visible' => true, 'order' => 0, 'labelSide' => 'start', 'valueSide' => 'end'],
                                ['id' => 'date', 'field' => 'document.date',   'label' => 'التاريخ',      'visible' => true, 'order' => 1, 'labelSide' => 'start', 'valueSide' => 'end'],
                                ['id' => 'ttc',  'field' => 'totals.ttc',      'label' => 'المبلغ',       'visible' => true, 'order' => 2, 'labelSide' => 'start', 'valueSide' => 'end', 'bold' => true],
                            ],
                        ],
                    ],
                ],
                'totals_grid' => [
                    'enabled' => true,
                    'headerBg' => '#1a1a2e',
                    'headerColor' => '#ffffff',
                    'borderColor' => '#333333',
                    'columns' => [
                        ['id' => 'c1', 'field' => 'grid.baseExcl',      'label' => 'المبلغ خارج الرسم', 'order' => 0, 'visible' => true, 'align' => 'center'],
                        ['id' => 'c2', 'field' => 'grid.discountPct',    'label' => 'التخفيض',          'order' => 1, 'visible' => true, 'align' => 'center'],
                        ['id' => 'c3', 'field' => 'grid.discountAmount', 'label' => 'مبلغ التخفيض',      'order' => 2, 'visible' => true, 'align' => 'center'],
                        ['id' => 'c4', 'field' => 'grid.tvaRate',        'label' => 'TVA',              'order' => 3, 'visible' => true, 'align' => 'center'],
                        ['id' => 'c5', 'field' => 'grid.tvaAmount',      'label' => 'مبلغ TVA',         'order' => 4, 'visible' => true, 'align' => 'center'],
                    ],
                    'summaryRows' => [
                        ['id' => 'total_ht', 'field' => 'totals.ht',       'label' => 'المجموع بدون رسوم', 'visible' => true, 'order' => 0, 'labelSide' => 'start', 'valueSide' => 'end'],
                        ['id' => 'discount', 'field' => 'totals.discount', 'label' => 'مجموع التخفيض',     'visible' => true, 'order' => 1, 'labelSide' => 'start', 'valueSide' => 'end'],
                        ['id' => 'tva',      'field' => 'totals.tva',      'label' => 'مجموع الضريبة',     'visible' => true, 'order' => 2, 'labelSide' => 'start', 'valueSide' => 'end'],
                        ['id' => 'ttc',      'field' => 'totals.ttc',      'label' => 'الصافي للدفع',      'visible' => true, 'order' => 3, 'labelSide' => 'start', 'valueSide' => 'end', 'bold' => true,
                            'border' => ['style' => 'double', 'width' => 3, 'color' => '#111', 'sides' => ['top' => true]]],
                    ],
                ],
            ],
        ],
        'dz-delivery-a4' => [
            'name'          => 'وصل التسليم الجزائري A4',
            'doc_type_code' => 'BL',
            'paper_size'    => 'A4',
            'is_default'    => false,
            'is_active'     => true,
            'config'        => [
                'paper_width_mm'       => 80,
                'page_orientation'     => 'portrait',
                'margin_top'           => 20,
                'margin_bottom'        => 20,
                'margin_sides'         => 18,
                'line_spacing'         => 1.2,
                'base_font_size'       => 9.5,
                'font_family'          => 'tajawal',
                'show_logo'            => true,
                'logo_source'          => 'company',
                'custom_logo_url'      => null,
                'logo_size'            => 75,
                'logo_align'           => 'left',
                'logo_border_radius'   => 0,
                'show_company_name'    => true,
                'company_name_text'    => '',
                'company_name_size'    => 16,
                'company_name_bold'    => true,
                'company_name_align'   => 'right',
                'company_name_color'   => '#1a1a2e',
                'show_address'         => true,
                'show_phone'           => true,
                'show_tax_id'          => true,
                'show_rc'              => true,
                'show_nis'             => true,
                'show_article'         => true,
                'company_info_align'   => 'right',
                'company_info_size'    => 8.5,
                'header_separator'     => 'solid',
                'title_text'           => 'وصل تسليم',
                'title_size'           => 20,
                'title_bold'           => true,
                'title_align'          => 'center',
                'title_color'          => '#1a1a2e',
                'show_doc_number'      => true,
                'show_date'            => true,
                'show_due_date'        => false,
                'show_client'          => true,
                'show_client_nif'      => true,
                'show_client_phone'    => true,
                'show_client_address'  => true,
                'show_delivery_address'=> true,
                'doc_separator'        => 'solid',
                'col_order'            => ['ref','name','quantity','price','tva','total'],
                'col_show'             => ['ref'=>true,'name'=>true,'quantity'=>true,'price'=>true,'tva'=>true,'total'=>true],
                'col_widths'           => ['ref'=>8,'name'=>28,'quantity'=>12,'price'=>16,'tva'=>12,'total'=>18],
                'col_headers'          => ['ref'=>'م','name'=>'البيان','quantity'=>'الكمية','price'=>'س.و.ح','tva'=>'%TVA','total'=>'المبلغ'],
                'col_aligns'           => ['ref'=>'center','name'=>'right','quantity'=>'center','price'=>'center','tva'=>'center','total'=>'center'],
                'items_font_size'      => 9,
                'table_header_bg'      => '#1a1a2e',
                'table_header_color'   => '#ffffff',
                'table_border_style'   => 'solid',
                'alternating_rows'     => true,
                'alternating_color'    => '#f8f9fa',
                'totals_font_size'     => 10,
                'totals_bold'          => true,
                'totals_align'         => 'left',
                'show_total_ht'        => true,
                'show_total_tva'       => true,
                'show_tva_breakdown'   => true,
                'show_discount_total'  => true,
                'show_fiscal_stamp'    => true,
                'show_total_ttc'       => true,
                'total_ttc_font_size'  => 17,
                'total_ttc_bold'       => true,
                'total_ttc_color'      => '#1a1a2e',
                'total_border_style'   => 'double',
                'show_amount_in_words' => true,
                'footer_line1'         => 'البضاعة المسلمة لا ترد ولا تستبدل',
                'footer_line2'         => 'التوقيع: إمضاء المخزن / إمضاء الزبون',
                'footer_separator'     => 'solid',
                'show_thank_you'       => true,
                'thank_you_text'       => 'شكراً لتعاملكم',
                'show_returns_policy'  => true,
                'returns_policy_text'  => 'البضاعة المسلمة لا ترد ولا تستبدل',
                'show_barcode'         => true,
                'barcode_content'      => 'doc-number',
                'show_qr'              => true,
                'qr_content'           => 'both',
                'show_cashier_signature'=> true,
                'show_client_signature' => true,
                'show_stamp'           => true,
                'show_header_section'  => true,
                'show_doc_info_section'=> true,
                'show_items_section'   => true,
                'show_totals_section'  => true,
                'show_footer_section'  => true,
                'rules'                => [],
            ],
        ],
        'dz-delivery-a5' => [
            'name'          => 'وصل التسليم الجزائري A5',
            'doc_type_code' => 'BL',
            'paper_size'    => 'A5',
            'is_default'    => false,
            'is_active'     => true,
            'config'        => [
                'paper_width_mm'       => 80,
                'page_orientation'     => 'portrait',
                'margin_top'           => 12,
                'margin_bottom'        => 12,
                'margin_sides'         => 12,
                'line_spacing'         => 1.2,
                'base_font_size'       => 8.5,
                'font_family'          => 'tajawal',
                'show_logo'            => true,
                'logo_size'            => 75,
                'logo_align'           => 'left',
                'show_company_name'    => true,
                'company_name_size'    => 13,
                'company_name_bold'    => true,
                'company_name_color'   => '#1a1a2e',
                'title_text'           => 'وصل تسليم',
                'title_size'           => 16,
                'title_bold'           => true,
                'title_align'          => 'center',
                'title_color'          => '#1a1a2e',
                'col_order'            => ['ref','name','quantity','price','total'],
                'col_widths'           => ['ref'=>8,'name'=>32,'quantity'=>14,'price'=>20,'total'=>22],
                'col_headers'          => ['ref'=>'م','name'=>'البيان','quantity'=>'الكمية','price'=>'س.و.ح','total'=>'المبلغ'],
                'items_font_size'      => 8,
                'table_header_bg'      => '#1a1a2e',
                'table_header_color'   => '#ffffff',
                'table_border_style'   => 'solid',
                'alternating_rows'     => true,
                'alternating_color'    => '#f8f9fa',
                'totals_font_size'     => 9,
                'totals_bold'          => true,
                'totals_align'         => 'left',
                'show_total_ht'        => true,
                'show_total_tva'       => true,
                'show_total_ttc'       => true,
                'total_ttc_font_size'  => 14,
                'total_ttc_bold'       => true,
                'total_ttc_color'      => '#1a1a2e',
                'total_border_style'   => 'double',
                'footer_line1'         => 'البضاعة المسلمة لا ترد ولا تستبدل',
                'footer_separator'     => 'solid',
                'show_thank_you'       => true,
                'thank_you_text'       => 'شكراً',
                'show_barcode'         => true,
                'show_qr'              => true,
                'show_cashier_signature'=> true,
                'show_client_signature' => true,
                'show_stamp'           => true,
                'show_header_section'  => true,
                'show_doc_info_section'=> true,
                'show_items_section'   => true,
                'show_totals_section'  => true,
                'show_footer_section'  => true,
                'rules'                => [],
            ],
        ],
        'dz-quote-a4' => [
            'name'          => 'عرض السعر الجزائري A4',
            'doc_type_code' => 'DEV',
            'paper_size'    => 'A4',
            'is_default'    => false,
            'is_active'     => true,
            'config'        => [
                'paper_width_mm'       => 80,
                'page_orientation'     => 'portrait',
                'margin_top'           => 18,
                'margin_bottom'        => 18,
                'margin_sides'         => 18,
                'line_spacing'         => 1.25,
                'base_font_size'       => 9.5,
                'font_family'          => 'tajawal',
                'show_logo'            => true,
                'logo_source'          => 'company',
                'logo_size'            => 70,
                'logo_align'           => 'left',
                'logo_border_radius'   => 0,
                'show_company_name'    => true,
                'company_name_text'    => '',
                'company_name_size'    => 14,
                'company_name_bold'    => true,
                'company_name_align'   => 'right',
                'company_name_color'   => '#1a1a2e',
                'show_address'         => true,
                'show_phone'           => true,
                'show_tax_id'          => true,
                'show_rc'              => true,
                'show_nis'             => true,
                'company_info_align'   => 'right',
                'company_info_size'    => 8.5,
                'header_separator'     => 'solid',
                'title_text'           => 'عرض سعر',
                'title_size'           => 20,
                'title_bold'           => true,
                'title_align'          => 'center',
                'title_color'          => '#1a1a2e',
                'show_doc_number'      => true,
                'show_date'            => true,
                'show_due_date'        => false,
                'show_client'          => true,
                'show_client_nif'      => true,
                'show_client_address'  => true,
                'show_delivery_address'=> false,
                'show_payment_term'    => true,
                'payment_term_text'    => 'شروط الدفع: 30 يوماً من تاريخ عرض السعر',
                'doc_separator'        => 'dashed',
                'col_order'            => ['ref','name','quantity','price','total'],
                'col_show'             => ['ref'=>true,'name'=>true,'quantity'=>true,'price'=>true,'total'=>true],
                'col_widths'           => ['ref'=>8,'name'=>34,'quantity'=>10,'price'=>18,'total'=>18],
                'col_headers'          => ['ref'=>'م','name'=>'البيان','quantity'=>'الكمية','price'=>'س.و.ح','total'=>'المبلغ'],
                'col_aligns'           => ['ref'=>'center','name'=>'right','quantity'=>'center','price'=>'center','total'=>'center'],
                'items_font_size'      => 9,
                'show_col_header'      => true,
                'table_header_bold'    => true,
                'table_header_bg'      => '#2c3e50',
                'table_header_color'   => '#ffffff',
                'table_border_style'   => 'solid',
                'alternating_rows'     => true,
                'alternating_color'    => '#f8f9fa',
                'price_display'        => 'ht',
                'totals_font_size'     => 10,
                'totals_bold'          => true,
                'totals_align'         => 'left',
                'show_total_ht'        => true,
                'show_total_tva'       => true,
                'show_tva_breakdown'   => true,
                'show_discount_total'  => true,
                'show_fiscal_stamp'    => false,
                'show_total_ttc'       => true,
                'total_ttc_font_size'  => 15,
                'total_ttc_bold'       => true,
                'total_ttc_color'      => '#2c3e50',
                'total_border_style'   => 'double',
                'show_amount_in_words' => true,
                'footer_line1'         => 'هذا العرض صالح لمدة 30 يوماً من تاريخه',
                'footer_line2'         => 'للاستفسار اتصل على: 0550 00 00 00',
                'footer_separator'     => 'solid',
                'show_thank_you'       => true,
                'thank_you_text'       => 'شكراً لتعاملكم',
                'thank_you_size'       => 11,
                'thank_you_color'      => '#333333',
                'show_barcode'         => true,
                'barcode_content'      => 'doc-number',
                'show_qr'              => true,
                'qr_content'           => 'both',
                'show_stamp'           => true,
                'show_header_section'  => true,
                'show_doc_info_section'=> true,
                'show_items_section'   => true,
                'show_totals_section'  => true,
                'show_payments_section'=> false,
                'show_footer_section'  => true,
                'rules'                => [],
            ],
        ],
        'dz-purchase-order-a4' => [
            'name'          => 'أمر الشراء الجزائري A4',
            'doc_type_code' => 'AV',
            'paper_size'    => 'A4',
            'is_default'    => false,
            'is_active'     => true,
            'config'        => [
                'paper_width_mm'       => 80,
                'page_orientation'     => 'portrait',
                'margin_top'           => 18,
                'margin_bottom'        => 18,
                'margin_sides'         => 18,
                'line_spacing'         => 1.25,
                'base_font_size'       => 9.5,
                'font_family'          => 'tajawal',
                'show_logo'            => true,
                'logo_source'          => 'company',
                'logo_size'            => 70,
                'logo_align'           => 'left',
                'show_company_name'    => true,
                'company_name_size'    => 14,
                'company_name_bold'    => true,
                'company_name_align'   => 'right',
                'company_name_color'   => '#1a1a2e',
                'show_address'         => true,
                'show_phone'           => true,
                'show_tax_id'          => true,
                'show_rc'              => true,
                'header_separator'     => 'solid',
                'title_text'           => 'أمر شراء',
                'title_size'           => 20,
                'title_bold'           => true,
                'title_align'          => 'center',
                'title_color'          => '#1a1a2e',
                'show_doc_number'      => true,
                'show_date'            => true,
                'show_due_date'        => true,
                'show_client'          => true,
                'show_client_nif'      => true,
                'show_client_address'  => true,
                'show_delivery_address'=> true,
                'show_payment_term'    => true,
                'payment_term_text'    => 'شروط الدفع: حسب الاتفاق',
                'doc_separator'        => 'solid',
                'col_order'            => ['ref','name','quantity','price','total'],
                'col_show'             => ['ref'=>true,'name'=>true,'quantity'=>true,'price'=>true,'total'=>true],
                'col_widths'           => ['ref'=>8,'name'=>32,'quantity'=>12,'price'=>18,'total'=>18],
                'col_headers'          => ['ref'=>'م','name'=>'البيان','quantity'=>'الكمية','price'=>'س.و.ح','total'=>'المبلغ'],
                'col_aligns'           => ['ref'=>'center','name'=>'right','quantity'=>'center','price'=>'center','total'=>'center'],
                'items_font_size'      => 9,
                'show_col_header'      => true,
                'table_header_bold'    => true,
                'table_header_bg'      => '#34495e',
                'table_header_color'   => '#ffffff',
                'table_border_style'   => 'solid',
                'alternating_rows'     => true,
                'alternating_color'    => '#f8f9fa',
                'totals_font_size'     => 10,
                'totals_bold'          => true,
                'totals_align'         => 'left',
                'show_total_ht'        => true,
                'show_total_tva'       => true,
                'show_discount_total'  => true,
                'show_total_ttc'       => true,
                'total_ttc_font_size'  => 15,
                'total_ttc_bold'       => true,
                'total_ttc_color'      => '#34495e',
                'total_border_style'   => 'double',
                'show_amount_in_words' => false,
                'footer_line1'         => 'أمر شراء رسمي — يرجى الالتزام بالشروط المذكورة أعلاه',
                'footer_separator'     => 'solid',
                'show_thank_you'       => true,
                'thank_you_text'       => 'شكراً',
                'show_barcode'         => true,
                'barcode_content'      => 'doc-number',
                'show_qr'              => true,
                'qr_content'           => 'both',
                'show_cashier_signature'=> true,
                'show_client_signature' => true,
                'show_stamp'           => true,
                'show_header_section'  => true,
                'show_doc_info_section'=> true,
                'show_items_section'   => true,
                'show_totals_section'  => true,
                'show_footer_section'  => true,
                'rules'                => [],
            ],
        ],
        'dz-purchase-invoice-a4' => [
            'name'          => 'فاتورة الشراء الجزائرية A4',
            'doc_type_code' => 'FA',
            'paper_size'    => 'A4',
            'is_default'    => false,
            'is_active'     => true,
            'config'        => [
                'paper_width_mm'       => 80,
                'page_orientation'     => 'portrait',
                'margin_top'           => 18,
                'margin_bottom'        => 18,
                'margin_sides'         => 18,
                'line_spacing'         => 1.2,
                'base_font_size'       => 9.5,
                'font_family'          => 'tajawal',
                'show_logo'            => true,
                'logo_source'          => 'company',
                'logo_size'            => 75,
                'logo_align'           => 'left',
                'show_company_name'    => true,
                'company_name_size'    => 16,
                'company_name_bold'    => true,
                'company_name_color'   => '#1a1a2e',
                'show_address'         => true,
                'show_phone'           => true,
                'show_tax_id'          => true,
                'show_rc'              => true,
                'company_info_size'    => 8.5,
                'header_separator'     => 'solid',
                'title_text'           => 'فاتورة شراء',
                'title_size'           => 20,
                'title_bold'           => true,
                'title_align'          => 'center',
                'title_color'          => '#1a1a2e',
                'show_doc_number'      => true,
                'show_date'            => true,
                'show_due_date'        => true,
                'show_client'          => true,
                'show_client_nif'      => true,
                'show_client_address'  => true,
                'show_delivery_address'=> false,
                'doc_separator'        => 'solid',
                'col_order'            => ['ref','name','quantity','price','tva','total'],
                'col_show'             => ['ref'=>true,'name'=>true,'quantity'=>true,'price'=>true,'tva'=>true,'total'=>true],
                'col_widths'           => ['ref'=>8,'name'=>28,'quantity'=>10,'price'=>18,'tva'=>12,'total'=>18],
                'col_headers'          => ['ref'=>'م','name'=>'البيان','quantity'=>'الكمية','price'=>'س.و.ح','tva'=>'%TVA','total'=>'المبلغ'],
                'col_aligns'           => ['ref'=>'center','name'=>'right','quantity'=>'center','price'=>'center','tva'=>'center','total'=>'center'],
                'items_font_size'      => 9,
                'show_col_header'      => true,
                'table_header_bold'    => true,
                'table_header_bg'      => '#1a1a2e',
                'table_header_color'   => '#ffffff',
                'table_border_style'   => 'solid',
                'alternating_rows'     => true,
                'alternating_color'    => '#f8f9fa',
                'totals_font_size'     => 10,
                'totals_bold'          => true,
                'totals_align'         => 'left',
                'show_total_ht'        => true,
                'show_total_tva'       => true,
                'show_tva_breakdown'   => true,
                'show_discount_total'  => true,
                'show_fiscal_stamp'    => false,
                'show_total_ttc'       => true,
                'total_ttc_font_size'  => 17,
                'total_ttc_bold'       => true,
                'total_ttc_color'      => '#1a1a2e',
                'total_border_style'   => 'double',
                'show_amount_in_words' => true,
                'footer_line1'         => 'فاتورة شراء رسمية',
                'footer_separator'     => 'solid',
                'show_thank_you'       => true,
                'thank_you_text'       => 'شكراً',
                'show_barcode'         => true,
                'barcode_content'      => 'doc-number',
                'show_qr'              => true,
                'qr_content'           => 'both',
                'show_cashier_signature'=> true,
                'show_stamp'           => true,
                'show_header_section'  => true,
                'show_doc_info_section'=> true,
                'show_items_section'   => true,
                'show_totals_section'  => true,
                'show_footer_section'  => true,
                'rules'                => [],
            ],
        ],
        'dz-sticker-label' => [
            'name'          => 'ملصق المنتج 400×200mm',
            'doc_type_code' => 'STK',
            'paper_size'    => '400x200mm',
            'is_default'    => false,
            'is_active'     => true,
            'config'        => [
                'paper_width_mm'          => 80,
                'page_orientation'        => 'portrait',
                'margin_top'              => 6,
                'margin_bottom'           => 6,
                'margin_sides'            => 8,
                'line_spacing'            => 1.1,
                'base_font_size'          => 12,
                'font_family'             => 'tajawal',
                'show_logo'               => true,
                'logo_source'             => 'company',
                'custom_logo_url'         => null,
                'logo_size'               => 50,
                'logo_align'              => 'center',
                'logo_border_radius'      => 0,
                'show_company_name'       => true,
                'company_name_text'       => '',
                'company_name_size'       => 13,
                'company_name_bold'       => true,
                'company_name_align'      => 'center',
                'company_name_color'      => '#1a1a2e',
                'show_address'            => false,
                'show_phone'              => false,
                'show_tax_id'             => false,
                'show_rc'                 => false,
                'show_nis'                => false,
                'show_ice'                => false,
                'show_article'            => false,
                'company_info_align'      => 'center',
                'company_info_size'       => 9,
                'header_custom_text'      => '',
                'header_separator'        => 'dashed',
                'title_text'              => '',
                'title_size'              => 14,
                'title_bold'              => false,
                'title_align'             => 'center',
                'title_color'             => '#111',
                'show_doc_number'         => false,
                'show_date'               => false,
                'show_time'               => false,
                'show_due_date'           => false,
                'show_cashier'            => false,
                'show_client'             => false,
                'show_client_nif'         => false,
                'show_client_phone'       => false,
                'show_client_address'     => false,
                'show_delivery_address'   => false,
                'show_session'            => false,
                'show_payment_term'       => false,
                'show_bank_details'       => false,
                'bank_details_text'       => '',
                'doc_separator'           => 'none',
                'col_order'               => ['name','price'],
                'col_show'                => ['name'=>true,'price'=>true],
                'col_widths'              => ['name'=>50,'price'=>50],
                'col_headers'             => ['name'=>'البيان','price'=>'السعر'],
                'col_aligns'              => ['name'=>'center','price'=>'center'],
                'items_font_size'         => 9,
                'items_font_family'       => 'tajawal',
                'show_col_header'         => false,
                'table_header_bold'       => true,
                'table_header_bg'         => '#333',
                'table_header_color'      => '#fff',
                'table_border_style'      => 'none',
                'alternating_rows'        => false,
                'alternating_color'       => '#f8f9fa',
                'price_display'           => 'ttc',
                'show_line_total_ttc'     => false,
                'totals_font_size'        => 11,
                'totals_bold'             => true,
                'totals_align'            => 'center',
                'show_total_ht'           => false,
                'show_total_tva'          => false,
                'show_tva_breakdown'      => false,
                'show_discount_total'     => false,
                'show_fiscal_stamp'       => false,
                'show_total_ttc'          => false,
                'total_ttc_font_size'     => 14,
                'total_ttc_bold'          => true,
                'total_ttc_color'         => '#c0392b',
                'total_border_style'      => 'none',
                'show_amount_in_words'    => false,
                'show_paid_amount'        => false,
                'show_change'             => false,
                'show_remaining'          => false,
                'show_prev_balance'       => false,
                'show_new_balance'        => false,
                'show_payment_details'    => false,
                'payment_font_size'       => 9,
                'footer_line1'            => '',
                'footer_line2'            => '',
                'footer_line3'            => '',
                'footer_separator'        => 'none',
                'show_thank_you'          => false,
                'thank_you_text'          => '',
                'thank_you_size'          => 10,
                'thank_you_color'         => '#666',
                'show_returns_policy'     => false,
                'returns_policy_text'     => '',
                'footer_legal_text'       => '',
                'show_barcode'            => false,
                'barcode_content'         => 'doc-number',
                'barcode_custom_text'     => '',
                'show_qr'                 => false,
                'qr_content'              => 'both',
                'show_cashier_signature'  => false,
                'show_client_signature'   => false,
                'show_stamp'              => false,
                'show_header_section'     => true,
                'show_doc_info_section'   => false,
                'show_items_section'      => false,
                'show_totals_section'     => false,
                'show_payments_section'   => false,
                'show_footer_section'     => false,
                'rules'                   => [],
                'show_label_barcode'      => true,
                'show_label_product_name' => true,
                'show_label_ref'          => true,
                'show_label_price'        => true,
                'label_product_name_size' => 16,
                'label_product_name_bold' => true,
                'label_product_name_color'=> '#111',
                'label_ref_size'          => 9,
                'label_ref_color'         => '#666',
                'label_price_size'        => 28,
                'label_price_bold'        => true,
                'label_price_color'       => '#c0392b',
                'label_barcode_height'    => 45,
                'label_border_style'      => 'solid',
                'label_border_width'      => 1,
                'label_border_color'      => '#333',
                'label_border_radius'     => 6,
                'label_price_prefix'      => '',
                'label_price_text'        => 'DA',
            ],
        ],
    ];

    public static function getMetadata(): array
    {
        $metas = [
            'dz-invoice-a4' => [
                'id'            => 'dz-invoice-a4',
                'name'          => 'Algerian Invoice A4',
                'name_ar'       => 'الفاتورة الجزائرية A4',
                'description'   => 'Standard Algerian fiscal invoice in A4 format with full TVA breakdown, fiscal stamp, amount in words, signature and QR code.',
                'description_ar'=> 'فاتورة بيع جزائرية رسمية بصيغة A4 مع تفصيل TVA والطابع الجبائي والمبلغ كتابة والتوقيع ورمز QR',
                'document_type' => 'FV',
                'paper_size'    => 'A4',
                'category'      => 'invoices',
                'tags'          => ['algeria', 'arabic', 'fiscal', 'official', 'tva', 'qrcode', 'barcode', 'signature', 'invoice', 'a4'],
                'version'       => '1.0.0',
                'revision'      => 1,
                'country'       => 'DZ',
                'author'        => 'erp-system',
                'read_only'     => true,
            ],
            'dz-delivery-a4' => [
                'id'            => 'dz-delivery-a4',
                'name'          => 'Algerian Delivery Note A4',
                'name_ar'       => 'وصل التسليم الجزائري A4',
                'description'   => 'Standard Algerian delivery note in A4 format with detailed items table, TVA breakdown and signature block.',
                'description_ar'=> 'وصل تسليم جزائري رسمي بصيغة A4 مع جدول المواد وتفصيل TVA والتوقيع',
                'document_type' => 'BL',
                'paper_size'    => 'A4',
                'category'      => 'delivery-notes',
                'tags'          => ['algeria', 'arabic', 'fiscal', 'official', 'tva', 'qrcode', 'barcode', 'signature', 'delivery', 'a4'],
                'version'       => '1.0.0',
                'revision'      => 1,
                'country'       => 'DZ',
                'author'        => 'erp-system',
                'read_only'     => true,
            ],
            'dz-delivery-a5' => [
                'id'            => 'dz-delivery-a5',
                'name'          => 'Algerian Delivery Note A5',
                'name_ar'       => 'وصل التسليم الجزائري A5',
                'description'   => 'Compact Algerian delivery note in A5 half-page format with items table, TVA and signature block.',
                'description_ar'=> 'وصل تسليم جزائري بصيغة A5 بنصف صفحة مع جدول المواد و TVA والتوقيع',
                'document_type' => 'BL',
                'paper_size'    => 'A5',
                'category'      => 'delivery-notes',
                'tags'          => ['algeria', 'arabic', 'fiscal', 'official', 'delivery', 'a5'],
                'version'       => '1.0.0',
                'revision'      => 1,
                'country'       => 'DZ',
                'author'        => 'erp-system',
                'read_only'     => true,
            ],
            'dz-quote-a4' => [
                'id'            => 'dz-quote-a4',
                'name'          => 'Algerian Quote A4 (DEV)',
                'name_ar'       => 'عرض السعر الجزائري A4',
                'description'   => 'Professional Algerian quote in A4 with company header, detailed items table, payment terms and signature block.',
                'description_ar'=> 'عرض سعر جزائري احترافي بصيغة A4 مع رأس الشركة وجدول تفصيلي وشروط الدفع والتوقيع',
                'document_type' => 'DEV',
                'paper_size'    => 'A4',
                'category'      => 'quotes',
                'tags'          => ['algeria', 'arabic', 'professional', 'quote', 'dev', 'a4'],
                'version'       => '1.0.0',
                'revision'      => 1,
                'country'       => 'DZ',
                'author'        => 'erp-system',
                'read_only'     => true,
            ],
            'dz-purchase-order-a4' => [
                'id'            => 'dz-purchase-order-a4',
                'name'          => 'Algerian Purchase Order A4 (AV)',
                'name_ar'       => 'أمر الشراء الجزائري A4',
                'description'   => 'Official Algerian purchase order in A4 with company details, items table, delivery address and signature block.',
                'description_ar'=> 'أمر شراء جزائري رسمي بصيغة A4 مع تفاصيل الشركة وجدول المواد وعنوان التسليم والتوقيع',
                'document_type' => 'AV',
                'paper_size'    => 'A4',
                'category'      => 'purchase-orders',
                'tags'          => ['algeria', 'arabic', 'official', 'purchase-order', 'av', 'a4'],
                'version'       => '1.0.0',
                'revision'      => 1,
                'country'       => 'DZ',
                'author'        => 'erp-system',
                'read_only'     => true,
            ],
            'dz-purchase-invoice-a4' => [
                'id'            => 'dz-purchase-invoice-a4',
                'name'          => 'Algerian Purchase Invoice A4 (FA)',
                'name_ar'       => 'فاتورة الشراء الجزائرية A4',
                'description'   => 'Standard Algerian purchase invoice in A4 with full TVA breakdown, items table and signature block.',
                'description_ar'=> 'فاتورة شراء جزائرية رسمية بصيغة A4 مع تفصيل TVA وجدول المواد والتوقيع',
                'document_type' => 'FA',
                'paper_size'    => 'A4',
                'category'      => 'invoices',
                'tags'          => ['algeria', 'arabic', 'fiscal', 'official', 'purchase', 'fa', 'a4'],
                'version'       => '1.0.0',
                'revision'      => 1,
                'country'       => 'DZ',
                'author'        => 'erp-system',
                'read_only'     => true,
            ],
            'dz-sticker-label' => [
                'id'            => 'dz-sticker-label',
                'name'          => 'Algerian Product Label 400×200mm (STK)',
                'name_ar'       => 'ملصق المنتج 400×200mm',
                'description'   => 'Product price label for 400×200mm thermal label printers with barcode, product name, price, and company logo.',
                'description_ar'=> 'ملصق سعر المنتج لطابعات الليبل الحرارية 400×200mm مع الباركود واسم المنتج والسعر وشعار الشركة',
                'document_type' => 'STK',
                'paper_size'    => '400x200mm',
                'category'      => 'labels',
                'tags'          => ['algeria', 'arabic', 'label', 'sticker', 'barcode', 'product', 'price', '400x200'],
                'version'       => '1.0.0',
                'revision'      => 1,
                'country'       => 'DZ',
                'author'        => 'erp-system',
                'read_only'     => true,
            ],
        ];

        return array_values($metas);
    }

    public static function find(string $templateId): ?array
    {
        return self::$templates[$templateId] ?? null;
    }

    public static function exists(string $templateId): bool
    {
        return isset(self::$templates[$templateId]);
    }

    public static function getConfig(string $templateId): ?array
    {
        $tpl = self::find($templateId);
        return $tpl ? $tpl['config'] : null;
    }

    public static function getFlatPayload(string $templateId): ?array
    {
        $tpl = self::find($templateId);
        if (!$tpl) return null;

        return [
            'name'          => $tpl['name'],
            'doc_type_code' => $tpl['doc_type_code'],
            'paper_size'    => $tpl['paper_size'],
            'is_default'    => $tpl['is_default'],
            'is_active'     => $tpl['is_active'],
            'config'        => $tpl['config'],
        ];
    }
}
