<?php

namespace App\Services;

class TemplateLibraryService
{
    /**
     * All built-in template definitions.
     * Each template is an immutable system asset — never stored in the DB.
     */
    private static array $templates = [
        'dz-invoice-a4' => [
            'name'          => 'فاتورة بيع A4',
            'doc_type_code' => 'FV',
            'paper_size'    => 'A4',
            'is_default'    => false,
            'is_active'     => true,
            'config'        => [
                'paper_width_mm'       => 80,
                'page_orientation'     => 'portrait',
                'margin_top'           => 20,
                'margin_bottom'        => 20,
                'margin_sides'         => 18,
                'line_spacing'         => 1.2,
                'base_font_size'       => 9.5,
                'font_family'          => 'tajawal',

                'show_logo'            => true,
                'logo_source'          => 'company',
                'custom_logo_url'      => null,
                'logo_size'            => 75,
                'logo_align'           => 'left',
                'logo_border_radius'   => 0,

                'show_company_name'    => true,
                'company_name_text'    => '',
                'company_name_size'    => 16,
                'company_name_bold'    => true,
                'company_name_align'   => 'right',
                'company_name_color'   => '#1a1a2e',

                'show_address'         => true,
                'show_phone'           => true,
                'show_tax_id'          => true,
                'show_rc'              => true,
                'show_nis'             => true,
                'show_ice'             => true,
                'show_article'         => true,
                'company_info_align'   => 'right',
                'company_info_size'    => 8.5,

                'override_address'     => '',
                'override_phone'       => '',
                'override_nif'         => '',
                'override_rc'          => '',
                'override_nis'         => '',
                'override_ice'         => '',
                'override_article'     => '',
                'header_custom_text'   => '',
                'header_separator'     => 'solid',

                'title_text'           => 'فاتورة بيع',
                'title_size'           => 20,
                'title_bold'           => true,
                'title_align'          => 'center',
                'title_color'          => '#1a1a2e',
                'show_doc_number'      => true,
                'show_date'            => true,
                'show_time'            => false,
                'show_due_date'        => true,
                'show_cashier'         => true,
                'show_client'          => true,
                'show_client_nif'      => true,
                'show_client_phone'    => true,
                'show_client_address'  => true,
                'show_delivery_address'=> false,
                'show_session'         => false,
                'show_payment_term'    => false,
                'show_bank_details'    => true,
                'bank_details_text'    => 'RIB: 007 99999 000012345678 90',
                'doc_separator'        => 'solid',

                'col_order'            => ['ref','name','quantity','price','tva','total'],
                'col_show'             => ['ref'=>true,'name'=>true,'quantity'=>true,'price'=>true,'tva'=>true,'total'=>true],
                'col_widths'           => ['ref'=>8,'name'=>28,'quantity'=>10,'price'=>18,'tva'=>12,'total'=>18],
                'col_headers'          => ['ref'=>'م','name'=>'البيان','quantity'=>'الكمية','price'=>'س.و.ح','tva'=>'%TVA','total'=>'المبلغ'],
                'col_aligns'           => ['ref'=>'center','name'=>'right','quantity'=>'center','price'=>'center','tva'=>'center','total'=>'center'],

                'items_font_size'      => 9,
                'items_font_family'    => 'tajawal',
                'show_col_header'      => true,
                'table_header_bold'    => true,
                'table_header_bg'      => true,
                'table_header_color'   => '#1a1a2e',
                'table_border_style'   => 'solid',
                'alternating_rows'     => true,
                'alternating_color'    => '#f8f9fa',
                'price_display'        => 'ht',
                'show_line_total_ttc'  => false,

                'totals_font_size'     => 10,
                'totals_bold'          => true,
                'totals_align'         => 'left',
                'show_total_ht'        => true,
                'show_total_tva'       => true,
                'show_tva_breakdown'   => true,
                'show_discount_total'  => true,
                'show_fiscal_stamp'    => true,
                'show_total_ttc'       => true,
                'total_ttc_font_size'  => 17,
                'total_ttc_bold'       => true,
                'total_ttc_color'      => '#1a1a2e',
                'total_border_style'   => 'double',
                'show_amount_in_words' => true,
                'show_paid_amount'     => false,
                'show_change'          => false,
                'show_remaining'       => false,
                'show_prev_balance'    => false,
                'show_new_balance'     => false,

                'show_payment_details' => false,
                'payment_font_size'    => 9,

                'footer_line1'         => 'البضاعة المباعة لا ترد ولا تستبدل',
                'footer_line2'         => 'للاستفسار اتصل على: 0550 00 00 00',
                'footer_line3'         => '',
                'footer_separator'     => 'solid',
                'show_thank_you'       => true,
                'thank_you_text'       => 'شكراً لتعاملكم',
                'thank_you_size'       => 11,
                'thank_you_color'      => '#333333',
                'show_returns_policy'  => true,
                'returns_policy_text'  => 'البضاعة المباعة لا ترد ولا تستبدل',
                'footer_legal_text'    => '',

                'show_barcode'         => true,
                'barcode_content'      => 'doc-number',
                'barcode_custom_text'  => '',
                'show_qr'              => true,
                'qr_content'           => 'both',

                'show_cashier_signature'=> true,
                'show_client_signature' => true,
                'show_stamp'           => true,

                'show_header_section'  => true,
                'show_doc_info_section'=> true,
                'show_items_section'   => true,
                'show_totals_section'  => true,
                'show_payments_section'=> false,
                'show_footer_section'  => true,

                'rules'                => [],

                'show_report_header'        => false,
                'report_header_text'        => '',
                'show_report_footer'        => false,
                'report_footer_text'        => '',
                'show_charts'               => false,
                'chart_type'                => 'bar',
                'chart_title'               => '',
                'group_by'                  => '',
                'sort_by'                   => '',
                'sort_direction'            => 'asc',
                'show_report_period'        => false,
                'show_report_cashier'       => false,
                'show_report_summary_cards' => false,
                'show_report_payment_breakdown' => false,
                'show_report_top_products'  => false,
            ],
        ],
        'dz-delivery-a4' => [
            'name'          => 'وصل التسليم الجزائري A4',
            'doc_type_code' => 'BL',
            'paper_size'    => 'A4',
            'is_default'    => false,
            'is_active'     => true,
            'config'        => [
                'paper_width_mm'       => 80,
                'page_orientation'     => 'portrait',
                'margin_top'           => 20,
                'margin_bottom'        => 20,
                'margin_sides'         => 18,
                'line_spacing'         => 1.2,
                'base_font_size'       => 9.5,
                'font_family'          => 'tajawal',

                'show_logo'            => true,
                'logo_source'          => 'company',
                'custom_logo_url'      => null,
                'logo_size'            => 75,
                'logo_align'           => 'left',
                'logo_border_radius'   => 0,

                'show_company_name'    => true,
                'company_name_text'    => '',
                'company_name_size'    => 16,
                'company_name_bold'    => true,
                'company_name_align'   => 'right',
                'company_name_color'   => '#1a1a2e',

                'show_address'         => true,
                'show_phone'           => true,
                'show_tax_id'          => true,
                'show_rc'              => true,
                'show_nis'             => true,
                'show_ice'             => true,
                'show_article'         => true,
                'company_info_align'   => 'right',
                'company_info_size'    => 8.5,

                'override_address'     => '',
                'override_phone'       => '',
                'override_nif'         => '',
                'override_rc'          => '',
                'override_nis'         => '',
                'override_ice'         => '',
                'override_article'     => '',
                'header_custom_text'   => '',
                'header_separator'     => 'solid',

                'title_text'           => 'وصل تسليم',
                'title_size'           => 20,
                'title_bold'           => true,
                'title_align'          => 'center',
                'title_color'          => '#1a1a2e',
                'show_doc_number'      => true,
                'show_date'            => true,
                'show_time'            => false,
                'show_due_date'        => false,
                'show_cashier'         => false,
                'show_client'          => true,
                'show_client_nif'      => true,
                'show_client_phone'    => true,
                'show_client_address'  => true,
                'show_delivery_address'=> true,
                'show_session'         => false,
                'show_payment_term'    => false,
                'show_bank_details'    => false,
                'bank_details_text'    => '',
                'doc_separator'        => 'solid',

                'col_order'            => ['ref','name','quantity','price','tva','total'],
                'col_show'             => ['ref'=>true,'name'=>true,'quantity'=>true,'price'=>true,'tva'=>true,'total'=>true],
                'col_widths'           => ['ref'=>8,'name'=>28,'quantity'=>12,'price'=>16,'tva'=>12,'total'=>18],
                'col_headers'          => ['ref'=>'م','name'=>'البيان','quantity'=>'الكمية','price'=>'س.و.ح','tva'=>'%TVA','total'=>'المبلغ'],
                'col_aligns'           => ['ref'=>'center','name'=>'right','quantity'=>'center','price'=>'center','tva'=>'center','total'=>'center'],

                'items_font_size'      => 9,
                'items_font_family'    => 'tajawal',
                'show_col_header'      => true,
                'table_header_bold'    => true,
                'table_header_bg'      => true,
                'table_header_color'   => '#1a1a2e',
                'table_border_style'   => 'solid',
                'alternating_rows'     => true,
                'alternating_color'    => '#f8f9fa',
                'price_display'        => 'ht',
                'show_line_total_ttc'  => false,

                'totals_font_size'     => 10,
                'totals_bold'          => true,
                'totals_align'         => 'left',
                'show_total_ht'        => true,
                'show_total_tva'       => true,
                'show_tva_breakdown'   => true,
                'show_discount_total'  => true,
                'show_fiscal_stamp'    => true,
                'show_total_ttc'       => true,
                'total_ttc_font_size'  => 17,
                'total_ttc_bold'       => true,
                'total_ttc_color'      => '#1a1a2e',
                'total_border_style'   => 'double',
                'show_amount_in_words' => true,
                'show_paid_amount'     => false,
                'show_change'          => false,
                'show_remaining'       => false,
                'show_prev_balance'    => false,
                'show_new_balance'     => false,

                'show_payment_details' => false,
                'payment_font_size'    => 9,

                'footer_line1'         => 'البضاعة المسلمة لا ترد ولا تستبدل',
                'footer_line2'         => 'التوقيع: إمضاء المخزن / إمضاء الزبون',
                'footer_line3'         => '',
                'footer_separator'     => 'solid',
                'show_thank_you'       => true,
                'thank_you_text'       => 'شكراً لتعاملكم',
                'thank_you_size'       => 11,
                'thank_you_color'      => '#333333',
                'show_returns_policy'  => true,
                'returns_policy_text'  => 'البضاعة المسلمة لا ترد ولا تستبدل',
                'footer_legal_text'    => '',

                'show_barcode'         => true,
                'barcode_content'      => 'doc-number',
                'barcode_custom_text'  => '',
                'show_qr'              => true,
                'qr_content'           => 'both',

                'show_cashier_signature'=> true,
                'show_client_signature' => true,
                'show_stamp'           => true,

                'show_header_section'  => true,
                'show_doc_info_section'=> true,
                'show_items_section'   => true,
                'show_totals_section'  => true,
                'show_payments_section'=> false,
                'show_footer_section'  => true,

                'rules'                => [],

                'show_report_header'        => false,
                'report_header_text'        => '',
                'show_report_footer'        => false,
                'report_footer_text'        => '',
                'show_charts'               => false,
                'chart_type'                => 'bar',
                'chart_title'               => '',
                'group_by'                  => '',
                'sort_by'                   => '',
                'sort_direction'            => 'asc',
                'show_report_period'        => false,
                'show_report_cashier'       => false,
                'show_report_summary_cards' => false,
                'show_report_payment_breakdown' => false,
                'show_report_top_products'  => false,
            ],
        ],
        'dz-delivery-a5' => [
            'name'          => 'وصل التسليم الجزائري A5',
            'doc_type_code' => 'BL',
            'paper_size'    => 'A5',
            'is_default'    => false,
            'is_active'     => true,
            'config'        => [
                'paper_width_mm'       => 80,
                'page_orientation'     => 'portrait',
                'margin_top'           => 12,
                'margin_bottom'        => 12,
                'margin_sides'         => 12,
                'line_spacing'         => 1.2,
                'base_font_size'       => 8.5,
                'font_family'          => 'tajawal',

                'show_logo'            => true,
                'logo_source'          => 'company',
                'custom_logo_url'      => null,
                'logo_size'            => 75,
                'logo_align'           => 'left',
                'logo_border_radius'   => 0,

                'show_company_name'    => true,
                'company_name_text'    => '',
                'company_name_size'    => 13,
                'company_name_bold'    => true,
                'company_name_align'   => 'right',
                'company_name_color'   => '#1a1a2e',

                'show_address'         => true,
                'show_phone'           => true,
                'show_tax_id'          => true,
                'show_rc'              => true,
                'show_nis'             => true,
                'show_ice'             => true,
                'show_article'         => true,
                'company_info_align'   => 'right',
                'company_info_size'    => 7.5,

                'override_address'     => '',
                'override_phone'       => '',
                'override_nif'         => '',
                'override_rc'          => '',
                'override_nis'         => '',
                'override_ice'         => '',
                'override_article'     => '',
                'header_custom_text'   => '',
                'header_separator'     => 'solid',

                'title_text'           => 'وصل تسليم',
                'title_size'           => 16,
                'title_bold'           => true,
                'title_align'          => 'center',
                'title_color'          => '#1a1a2e',
                'show_doc_number'      => true,
                'show_date'            => true,
                'show_time'            => false,
                'show_due_date'        => false,
                'show_cashier'         => false,
                'show_client'          => true,
                'show_client_nif'      => true,
                'show_client_phone'    => true,
                'show_client_address'  => true,
                'show_delivery_address'=> true,
                'show_session'         => false,
                'show_payment_term'    => false,
                'show_bank_details'    => false,
                'bank_details_text'    => '',
                'doc_separator'        => 'solid',

                'col_order'            => ['ref','name','quantity','price','total'],
                'col_show'             => ['ref'=>true,'name'=>true,'quantity'=>true,'price'=>true,'total'=>true],
                'col_widths'           => ['ref'=>8,'name'=>32,'quantity'=>14,'price'=>20,'total'=>22],
                'col_headers'          => ['ref'=>'م','name'=>'البيان','quantity'=>'الكمية','price'=>'س.و.ح','total'=>'المبلغ'],
                'col_aligns'           => ['ref'=>'center','name'=>'right','quantity'=>'center','price'=>'center','total'=>'center'],

                'items_font_size'      => 8,
                'items_font_family'    => 'tajawal',
                'show_col_header'      => true,
                'table_header_bold'    => true,
                'table_header_bg'      => true,
                'table_header_color'   => '#1a1a2e',
                'table_border_style'   => 'solid',
                'alternating_rows'     => true,
                'alternating_color'    => '#f8f9fa',
                'price_display'        => 'ht',
                'show_line_total_ttc'  => false,

                'totals_font_size'     => 9,
                'totals_bold'          => true,
                'totals_align'         => 'left',
                'show_total_ht'        => true,
                'show_total_tva'       => true,
                'show_tva_breakdown'   => false,
                'show_discount_total'  => true,
                'show_fiscal_stamp'    => false,
                'show_total_ttc'       => true,
                'total_ttc_font_size'  => 14,
                'total_ttc_bold'       => true,
                'total_ttc_color'      => '#1a1a2e',
                'total_border_style'   => 'double',
                'show_amount_in_words' => false,
                'show_paid_amount'     => false,
                'show_change'          => false,
                'show_remaining'       => false,
                'show_prev_balance'    => false,
                'show_new_balance'     => false,

                'show_payment_details' => false,
                'payment_font_size'    => 9,

                'footer_line1'         => 'البضاعة المسلمة لا ترد ولا تستبدل',
                'footer_line2'         => '',
                'footer_line3'         => '',
                'footer_separator'     => 'solid',
                'show_thank_you'       => true,
                'thank_you_text'       => 'شكراً',
                'thank_you_size'       => 10,
                'thank_you_color'      => '#333333',
                'show_returns_policy'  => true,
                'returns_policy_text'  => 'البضاعة المسلمة لا ترد ولا تستبدل',
                'footer_legal_text'    => '',

                'show_barcode'         => true,
                'barcode_content'      => 'doc-number',
                'barcode_custom_text'  => '',
                'show_qr'              => true,
                'qr_content'           => 'both',

                'show_cashier_signature'=> true,
                'show_client_signature' => true,
                'show_stamp'           => true,

                'show_header_section'  => true,
                'show_doc_info_section'=> true,
                'show_items_section'   => true,
                'show_totals_section'  => true,
                'show_payments_section'=> false,
                'show_footer_section'  => true,

                'rules'                => [],

                'show_report_header'        => false,
                'report_header_text'        => '',
                'show_report_footer'        => false,
                'report_footer_text'        => '',
                'show_charts'               => false,
                'chart_type'                => 'bar',
                'chart_title'               => '',
                'group_by'                  => '',
                'sort_by'                   => '',
                'sort_direction'            => 'asc',
                'show_report_period'        => false,
                'show_report_cashier'       => false,
                'show_report_summary_cards' => false,
                'show_report_payment_breakdown' => false,
                'show_report_top_products'  => false,
            ],
        ],
    ];

    public static function getMetadata(): array
    {
        $metas = [
            'dz-invoice-a4' => [
                'id'            => 'dz-invoice-a4',
                'name'          => 'Algerian Invoice A4',
                'name_ar'       => 'الفاتورة الجزائرية A4',
                'description'   => 'Standard Algerian fiscal invoice in A4 format with full TVA breakdown, fiscal stamp, amount in words, signature and QR code.',
                'description_ar'=> 'فاتورة بيع جزائرية رسمية بصيغة A4 مع تفصيل TVA والطابع الجبائي والمبلغ كتابة والتوقيع ورمز QR',
                'document_type' => 'FV',
                'paper_size'    => 'A4',
                'category'      => 'invoices',
                'subcategory'   => null,
                'tags'          => ['algeria', 'arabic', 'fiscal', 'official', 'tva', 'qrcode', 'barcode', 'signature', 'invoice', 'a4'],
                'version'       => '1.0.0',
                'revision'      => 1,
                'country'       => 'DZ',
                'author'        => 'erp-system',
                'read_only'     => true,
            ],
            'dz-delivery-a4' => [
                'id'            => 'dz-delivery-a4',
                'name'          => 'Algerian Delivery Note A4',
                'name_ar'       => 'وصل التسليم الجزائري A4',
                'description'   => 'Standard Algerian delivery note in A4 format with detailed items table, TVA breakdown and signature block.',
                'description_ar'=> 'وصل تسليم جزائري رسمي بصيغة A4 مع جدول المواد وتفصيل TVA والتوقيع',
                'document_type' => 'BL',
                'paper_size'    => 'A4',
                'category'      => 'delivery-notes',
                'subcategory'   => null,
                'tags'          => ['algeria', 'arabic', 'fiscal', 'official', 'tva', 'qrcode', 'barcode', 'signature', 'delivery', 'a4'],
                'version'       => '1.0.0',
                'revision'      => 1,
                'country'       => 'DZ',
                'author'        => 'erp-system',
                'read_only'     => true,
            ],
            'dz-delivery-a5' => [
                'id'            => 'dz-delivery-a5',
                'name'          => 'Algerian Delivery Note A5',
                'name_ar'       => 'وصل التسليم الجزائري A5',
                'description'   => 'Compact Algerian delivery note in A5 half-page format with items table, TVA and signature block.',
                'description_ar'=> 'وصل تسليم جزائري بصيغة A5 بنصف صفحة مع جدول المواد و TVA والتوقيع',
                'document_type' => 'BL',
                'paper_size'    => 'A5',
                'category'      => 'delivery-notes',
                'subcategory'   => null,
                'tags'          => ['algeria', 'arabic', 'fiscal', 'official', 'delivery', 'a5'],
                'version'       => '1.0.0',
                'revision'      => 1,
                'country'       => 'DZ',
                'author'        => 'erp-system',
                'read_only'     => true,
            ],
        ];

        return array_values($metas);
    }

    public static function find(string $templateId): ?array
    {
        return self::$templates[$templateId] ?? null;
    }

    public static function exists(string $templateId): bool
    {
        return isset(self::$templates[$templateId]);
    }

    public static function getConfig(string $templateId): ?array
    {
        $tpl = self::find($templateId);
        return $tpl ? $tpl['config'] : null;
    }

    public static function getFlatPayload(string $templateId): ?array
    {
        $tpl = self::find($templateId);
        if (!$tpl) return null;

        return [
            'name'          => $tpl['name'],
            'doc_type_code' => $tpl['doc_type_code'],
            'paper_size'    => $tpl['paper_size'],
            'is_default'    => $tpl['is_default'],
            'is_active'     => $tpl['is_active'],
            'config'        => $tpl['config'],
        ];
    }
}
