import type { UniversalDocumentData } from '../types/data';

let _mockCache: UniversalDocumentData | null = null;

export function getMockDocumentData(): UniversalDocumentData {
  if (_mockCache) return _mockCache;
  const data: UniversalDocumentData = {
    doc: {
      number:   'FV-2025-0001',
      date:     '28/06/2025',
      dueDate:  '28/07/2025',
      time:     '10:30',
      typeCode: 'FV',
      typeName: 'فاتورة بيع',
      status:   'confirmed',
      notes:    '',
      reference: '',
    },
    company: {
      name:    'المؤسسة الجزائرية',
      address: '15 شارع فلسطين، الجزائر العاصمة',
      phone:   '0550 00 00 00',
      nif:     '09991234567890',
      rc:      '99B1234567',
      nis:     '09991234567890',
      article: '1604123456',
      logoUrl: null,
      email:   'contact@entreprise.dz',
      website: '',
    },
    party: {
      id:              1,
      name:            'شركة نموذجية',
      type:            'client',
      nif:             '09991234567895',
      rc:              '',
      nis:             '',
      phone:           '0550 00 00 01',
      email:           '',
      address:         'شارع الاستقلال، الجزائر',
      deliveryAddress: '',
      cashierName:     '',
    },
    lines: [
      {
        rowNumber:  1,
        ref:        'REF001',
        barcode:    '123456789012',
        imageUrl:   null,
        brand:      'ماركة نموذجية',
        name:       'منتج نموذجي 1',
        unit:       'قطعة',
        quantity:   2,
        unitPriceHt: 5000,
        unitPriceTtc: 5950,
        tvaRate:    19,
        tvaPct:     19,
        discountPct: 0,
        discountAmt: 0,
        totalHt:    10000,
        totalTva:   1900,
        totalTtc:   11900,
        lot:        '',
        notes:      '',
      },
      {
        rowNumber:  2,
        ref:        'REF002',
        barcode:    '',
        name:       'منتج نموذجي 2',
        unit:       'قطعة',
        quantity:   1,
        unitPriceHt: 3500,
        unitPriceTtc: 3815,
        tvaRate:    9,
        tvaPct:     9,
        discountPct: 0,
        discountAmt: 0,
        totalHt:    3500,
        totalTva:   315,
        totalTtc:   3815,
        lot:        '',
        notes:      '',
      },
      {
        rowNumber:  3,
        ref:        'REF003',
        barcode:    '',
        name:       'منتج نموذجي 3',
        unit:       'قطعة',
        quantity:   5,
        unitPriceHt: 1200,
        unitPriceTtc: 1428,
        tvaRate:    19,
        tvaPct:     19,
        discountPct: 0,
        discountAmt: 0,
        totalHt:    6000,
        totalTva:   1140,
        totalTtc:   7140,
        lot:        '',
        notes:      '',
      },
    ],
    totals: {
      totalHt:      19500,
      totalTva:     3355,
      totalTtc:     23055,
      fiscalStamp:  200,
      totalDiscount: 0,
      paid:         0,
      change:       0,
      remaining:    23055,
    },
    taxBreakdown: [
      { rate: 19, baseHt: 16000, tva: 3040, ttc: 19040 },
      { rate: 9,  baseHt: 3500,  tva: 315,  ttc: 3815 },
    ],
    payments: [
      { mode: 'cash', amount: 23055, reference: '', date: '28/06/2025' },
    ],
  };
  _mockCache = data;
  return data;
}
